name: Testes Automatizados

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências (forçando peer deps)
        run: npm install --legacy-peer-deps

      - name: Rodar testes unitários com coverage
        run: jest tests/unit --coverage

